#cloud-config
package_update: true
packages:
  - git
  - ansible

runcmd:
  - git clone https://github.com/benocummins/rclone-offsite-ansible.git /opt/ansible-project
  - cd /opt/ansible-project
  - ansible-playbook -i inventory/hosts.ini playbooks/setup.yml
