---
- hosts: azure_vm
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install XFCE4, RDP Server and FUSE
      apt:
        name:
          - xfce4
          - xfce4-terminal
          - xrdp
          - fuse
          - fuse3
        state: present

    - name: Configure XRDP to use XFCE4
      copy:
        dest: /etc/xrdp/startwm.sh
        content: |
          #!/bin/sh
          # xrdp X session start script
          export DESKTOP_SESSION=xfce
          exec startxfce4
        mode: '0755'

    - name: Enable and start xrdp service
      systemd:
        name: xrdp
        enabled: true
        state: started

    - name: Add Rclone Repository and Install Rclone
      shell: |
        curl -fsSL https://rclone.org/install.sh | sudo bash
      args:
        creates: /usr/bin/rclone

    - name: Ensure rclone config directory exists
      file: 
        path: "/home/{{ ansible_user }}/.config/rclone"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"

    - name: Copy rclone config to remote server
      copy:
        src: "~/.config/rclone/rclone.conf"
        dest: "/home/{{ ansible_user }}/.config/rclone/rclone.conf"
        mode: '0600'
        owner: "{{ ansible_user }}"

    - name: Create rclone mount directory
      file:
        path: "/home/{{ ansible_user }}/rclone_mount"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"

    - name: Create systemd service for rclone mount
      copy:
        dest: /etc/systemd/system/rclone-mount.services
        content: |
          [Unit]
          Description=Rclone Mount Service
          After=network-online.target
          Wants=network-online.target

          [Service]
          Type=simple
          User={{ ansible_user }}
          ExecStart=/usr/bin/rclone mount b2-crypt: /home/{{ ansible_user }}/rclone-mount --vfs-cache-mode
          Restart=on-failure
          RestartSec=30

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Enable and start rclone mount service
      systemd:
        name: rclone-mount
        daemon_reload: yes
        enabled: true
        state: started