---
- hosts: azure_vm
  become: true
  tasks:
    - name: Add Rclone Repository
      shell: |
        curl -fsSL https://rclone.org/install.sh | sudo bash
      args:
        creates: /usr/bin/rclone

    - name: Ensure rclone config directory exists
      file: 
        path: "/home/{{ ansible_user }}/.config/rclone"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"

    - name: Copy rclone config to remote server
      copy:
        src: "~/.config/rclone/rclone.conf"
        dest: "/home/{{ ansible_user }}/.config/rclone/rclone.conf"
        mode: '0600'
        owner: "{{ ansible_user }}"

    - name: Update apt cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install XFCE4 and RDP Server
      apt:
        name:
          - xfce4
          - xfce4-terminal
          - xrdp
        state: present

    - name: Configure XRDP to use XFCE4
      copy:
        dest: /etc/xrdp/startwm.sh
        content: |
          #!/bin/sh
          # xrdp X session start script
          export DESKTOP_SESSION=xfce
          exec startxfce4
        mode: '0755'

    - name: Enable and start xrdp service
      systemd:
        name: xrdp
        enabled: true
        state: started