---
- hosts: azure_vm
  become: true
  tasks:
    - name: Add Rclone Repository
      shell: |
        curl -fsSL https://rclone.org/install.sh | sudo bash
      args:
        creates: /usr/bin/rclone

    - name: Ensure rclone config directory exists
      file: 
        path: "/home/{{ ansible_user }}/.config/rclone"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"

    - name: Copy rclone config to remote server
      copy:
        src: "~/.config/rclone/rclone.conf"
        dest: "/home/{{ ansible_user }}/.config/rclone/rclone.conf"
        mode: '0600'
        owner: "{{ ansible_user }}"

    - name: Install GUI and RDP Server
      apt:
        name:
          - ubuntu-desktop
          - xrdp
        state: present

    - name: Enable and start xrdp service
      systemd:
        name: xrdp
        enabled: true
        state: started