- hosts: azure_vm # Target host/group from ansible inventory file
  become: true # Run all tasks with sudo privileges - could be set on a task level if needed
  tasks:
    - name: Add Rclone Repository
      shell: |
        cur -fsSl https://rclone.org/install.sh | sudo bash # Download and run the rclone install script
      args:
        creates: /usr/bin/rclone

    - name: Ensure rclone config directory exists
      file: 
        path: "/home/{{ ansible_user }}/.config/rclone" # Path to rclone config directory
        state: directory # Ensure the directory exists
        mode: '0700' # Set secure permissions (owner read/write/execute only)
        owner: "{{ ansible_user }}" # Set ownership to the ansible user

    - name: Copy rclone.cong to remote server
      copy: # Ansible's copy module to transfer files
        src: ~/.config/rclone/rclone.conf #Source: GitHub Actions runner
        dest: "home/{{ ansible_user }}/.config/rclone/rclone.conf # Destination: Azure VM
        mode: '0600' # Set secure file permissions (owner read/write only)
        owner: "{{ ansible_user }}" # Set ownership to the ansible user

    - name: Install GUI and RDP Server
      apt:
        name: # Install multiple packages
          - ubuntu-desktop # Full Ubuntu GUI environment
          - xrdp # Remote Desktop Protocol server
        state: present

    - name: Enable and start xrpd service
      systemd: # Manage systemd services 
        name: xrdp
        enabled: true # Start on boot
        state: started # Ensure service is running now
