name: Ansible Deploy Rclone # Name shown in GitHub Actions UI

on:
  workflow_dispatch: # manual trigger only

permissions:
  actions: read # Needed to read artifacts
  contents: read # Needed to checkout code

jobs:
  deploy: # Define a job named 'deploy'
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      - name: Checkout repo #Get our code
        uses: actions/checkout@v4 # Official GitHub action to clone repo

      - name: Download Inventory File Artifact from Previous Workflow 
        uses: dawidd6/action-download-artifact@v6 # This action allows us to download artifacts from previous workflows without needing a PAT
        with:
          workflow: terraform-deploy.yml # Name of the workflow to download from
          name: ansible-inventory # Name of the artifact to download
          path: ./
          workflow_conclusion: success # Only download if the previous workflow was successful

      - name: Install Ansible # prepare environment
        run: sudo apt-get update && sudo apt-get install -y ansible sshpass # Install required

      - name: Setup SSH for Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.RSA_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Add SSH configuration to disable host key checking
          echo "Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Write rclone.conf from GitHub Secret # Configure rclone
        run: | # Multi-line command block
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG}}" > ~/.config/rclone/rclone.conf
          chmod 600 ~/.config/rclone/rclone.conf

      - name: Run Deploy Rclone Playbook # Execute Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini ./ansible/deploy-rclone-playbook.yml